### ISSUE TITLE
接続ボタンを押したタイミングでエラーが発生

### ISSUE THREAD

**Issue by a-kadoshima** [sakuraio/SakuraIOTest#9]
概要
手順に従いAPI Tokenなどを取得設定し、WebSocketsトークンを設定後、接続ボタンを押した時点でエラーが発生します。

実行環境
![image](https://user-images.githubusercontent.com/48306041/58310485-b5d32b00-7e41-11e9-9391-d53923bcfa35.png)

問題の内容
接続ボタンを押した際のエラーは以下になります。
![image](https://user-images.githubusercontent.com/48306041/58310932-cdf77a00-7e42-11e9-8280-d41da7f3bcee.png)

修正すべき内容
そもそも動作環境はWindows10以上などはありますでしょうか。
その他動かすための条件などがあれば、ブログ上に記載をお願いします。

**Comment by misodengaku** [comment]
READMEにも記載がある通り、Windows10以外での動作は確認していません。
WebSocket関連の動作がWindows7では実装されていないようなので非対応として明記することで対応します。

https://docs.microsoft.com/ja-jp/dotnet/api/system.net.websockets.websocket?redirectedfrom=MSDN&view=netframework-4.8
